language: python
services:
  - docker
python:
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential gfortran libatlas-base-dev liblapack-dev jq
script:
  - bash tests/fetch_test.sh
  - docker build --tag=kuropen/elecwarn-don:testing .
  - bash tests/docker_tz_test.sh
